######################################################################
# Automatically generated by qmake (3.0) Sun Dec 11 19:15:58 2016
######################################################################

TEMPLATE = app
TARGET = BullyProcess
INCLUDEPATH += .

# Input
HEADERS += Process.h stdafx.h targetver.h \
    ipcmanager.h \
    messege.h \
    timeHelper.h
SOURCES += Process.cpp \
    stdafx.cpp \
    main.cpp \
    ipcmanager.cpp \
    messege.cpp
